#Requires -Version 5.1
<#
.SYNOPSIS
  Write .env.local for Windows Vite → WSL Supabase.
  No Windows admin. Uses WSL IP (not localhost / not portproxy).
#>
$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot
$Distro = if ($env:LAMPFARMS_WSL_DISTRO) { $env:LAMPFARMS_WSL_DISTRO } else { 'Ubuntu' }

function Write-Info($m) { Write-Host "[stack:env] $m" -ForegroundColor Cyan }
function Write-Err($m)  { Write-Host "[stack:env] $m" -ForegroundColor Red }

if ($RepoRoot -match '^([A-Za-z]):\\(.*)$') {
  $drive = $Matches[1].ToLower()
  $rest = $Matches[2] -replace '\\', '/'
  $wslRepo = "/mnt/$drive/$rest"
} else {
  $wslRepo = $RepoRoot
}

$wslIp = (wsl -d $Distro -u root -e bash -lc "hostname -I | awk '{print `$1}'").Trim()
if (-not $wslIp) {
  Write-Err "Could not read WSL IP. Is Ubuntu installed?"
  exit 1
}

# Keys from supabase status (inside WSL where CLI lives)
$envText = wsl -d $Distro -u root -e bash -lc @"
export PATH=/opt/supabase-cli:/usr/local/bin:`$PATH
export SUPABASE_GO_BINARY=/opt/supabase-cli/supabase-go
cd $wslRepo
supabase status -o env 2>/dev/null || true
"@

$anon = $null
$pub = $null
if ($envText -match 'ANON_KEY="?([^"\r\n]+)"?') { $anon = $Matches[1].Trim() }
if ($envText -match 'PUBLISHABLE_KEY="?([^"\r\n]+)"?') { $pub = $Matches[1].Trim() }

# Local demo JWT always works for default supabase start
if (-not $anon) {
  $anon = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0'
}

$url = "http://${wslIp}:54321"
$envPath = Join-Path $RepoRoot '.env.local'

$content = @"
# Auto-generated by bun run stack:env — no Windows admin required
# WSL IP changes after wsl --shutdown; re-run stack:env after reboot
VITE_SUPABASE_URL=$url
VITE_SUPABASE_ANON_KEY=$anon
VITE_DEFAULT_CURRENCY=GHS
"@
if ($pub) {
  $content += "VITE_SUPABASE_PUBLISHABLE_KEY=$pub`n"
}

Set-Content -Path $envPath -Value $content -Encoding UTF8
Write-Info "Wrote $envPath"
Write-Info "VITE_SUPABASE_URL=$url"
Write-Info "Windows localhost:54321 is NOT used (Docker Engine in WSL)."
Write-Info "Restart Vite if it is already running."
